kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: {{ .Values.prefixPath }}/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 8080
status:
  loadBalancer: {}

